### ISSUE TITLE
Import from CSV decimal point issue

### ISSUE THREAD

**Issue by SkippyleGrandGourou** [litecart/litecart#107]
"Export To CSV" allows to select a language, but "Import From CSV" doesn't.  As a result, when one exports in a language with a decimal point set to comma, then imports the same file, decimals are discarded since the import uses a dot as decimal point.

Issue found in LiteCart 2.1.

**Comment by litecart** [comment]
Hi SkippyleGrandGourou.

Import doesn't need a language code since every row has the column language_code. So you could import info for several languages in one and same file.

LiteCart always outputs prices as a float value using decimal point. It should not collide with coma. Values that hold comas should be encapsulated using quotation marks. See the CSV standard for more info.
