### ISSUE TITLE
Notice "Issue"

### ISSUE THREAD

**Issue by Fefke** [litecart/litecart#132]
What were you trying to do?
I am trying to send a notice in the admin panel

What was expected to happen?
An Notice was shown up in the admin panel...

What was the actual result - what exactly did happen?
The Notice also showed up in an parrallel Session (no logins) on the homepage of litecart (in an another Tab) -> all without reloading! (any page)

Which LiteCart version are you running?
2.1.3

**Comment by timint** [comment]
Can you paste your error message from logs/errors.log?
How can this error be simulated?

**Comment by timint** [comment]
Notices is a stack bound to the browser session shared among several browser tabs opened. If you have multiple tabs open a notice can be visible in another tab while you posted data in a first tab. This can occur when a page is not rendered completely. Because the stack will not be dumped until the event after_capture(). see lib_notices.inc.php. A notice would not be seen in a different browser session than the one creating the notice.
