### ISSUE TITLE
Bad HTTPS detection in ent_link.inc.php

### ISSUE THREAD

**Issue by litecart-cs** [litecart/litecart#310]
### Description

Detection HTTPS does not work for load balancer/PROXY in ent_link.inc.php line 65.
my fix is add:

 || $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https'

More information: https://stackoverflow.com/questions/552162/detecting-https-vs-http-on-server-sending-back-nothing-useful#answer-552327

### LiteCart Version

LiteCart 2.5.2

### PHP Version

PHP 8.0

### Is this a problem that can be reproduced in the [demo platform](https://demo.litecart.net/admin)?

No

### If this problem could be related to a browser. Which one?

Not relevant

**Comment by timint** [comment]
This can not be added to the platform because it can be spoofed by passing by any request passing the header X-FORWARDED-PROTO which will be passed down to PHP as $_SERVER['HTTP_X_FORWARDED_PROTO']. But for those who rely on this, try adding the following to includes/compatibility.inc.php at the bottom:

```
  if (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https') {
    $_SERVER['HTTPS'] = 'on';
  }
```
