### ISSUE TITLE
Litecart appears to be out of business.

### ISSUE THREAD

**Issue by clrauto** [litecart/litecart#318]
### What where you trying to do?
No updates since 2022, Paypal and paypal express install into directories but do not show up in the modules. Wasted an entire day. Explain yourselves. 

If you're unreachable, there's no point in anyone working with you.

Shameful horrible experience. 

### LiteCart Version

latest

### PHP Version

Whatever you set it to on new installs.

### Error/Backtrace

```shell
NA
```

### Is this a problem that can be reproduced in the [demo platform](https://demo.litecart.net/admin)?

I don't know

### If this problem could be related to a browser. Which one?

Not relevant

**Comment by s22-tech** [comment]
Wow!  Where do I begin?  **No updates since 2022**???  Just quick glance at the code shows that the latest update was only 3 days ago.

**Shameful horrible experience**???  What are you talking about?  This is your first post here (not counting a comment on another thread).  You have ZERO posts on the LiteCart forum (at least under this name), so again, what are you talking about???

This is one of the most popular ecommerce scripts around and the developer is one of the most responsive people I've ever had the pleasure to work with.  You're either a very rude person, or you have no patience at all — or both.

If you're having problems with a PayPal add-on, post a message to the appropriate forum.  There are at lease 4 PayPal modules from different authors, so choose yours from here:

[PayPal Add-ons](https://www.litecart.net/en/addons?query=paypal)

Then click the Post A New Topic button and ask it there.  You will be taken care of - unless, of course, you continue to be rude.

Best of luck to you.

**Comment by xmexpi** [comment]
You are so ungrateful.. I understand that you were hoping for a more recent version of the ecommerce script. It's important to note that the latest version available for download is 2.5.3, which was released on April 25, 2023. The developer of this project, TIM, works tirelessly to provide the best possible experience for users. Despite being the sole contributor to the project, he makes it a priority to respond promptly to all inquiries. While I understand your concerns, please keep in mind that this is not a plug-and-play script like Shopify or WordPress. If this particular project is not meeting your needs, there may be other options that are a better fit for you.

**Comment by timint** [comment]
@clrauto You are speeding and making vast assumptions. The project is very much alive and I answer mail and forum posts each and every day. See the list of commits.
https://github.com/litecart/litecart/commits/dev

What comes to third party add-ons you will have to turn your questions to the author of the add-ons. There are a couple of Paypal implementations out there and mine is probably not the one you are hanging me for.
https://www.litecart.net/sv/addons?query=paypal

**Comment by apps4research** [comment]
@clrauto ... I really don't know what you are on about. I've only recently started using litecart and am very happy with it and also its support. It's really a very well made piece of software that is clean, lightweight and highly flexible as well as easy to adapt to one's own special needs. Before making false claims, maybe try the software first next time.
