### ISSUE TITLE
Admin "page refresh" v2a

### ISSUE THREAD

**Issue by gabbo2** [litecart/litecart#33]
When replacing the image in Admin->edit_category and edit_manufacturers, page does not "update", you must press "F5" to refresh.

**Comment by timint** [comment]
This is because the browser have cached the image. Not a bug. Not sure if it's a great idea to build a workaround for browser cache. It caches content by design. Cache serves a purpose.

You can setup a development platform if you need to play around with content without interfering with production.

**Comment by gabbo2** [comment]
No problem now that I know it works this way, I can set up a rule that not allows images to be cached in browser if it has "/admin" as a referer. :-)

**Comment by gabbo2** [comment]
Oops.. i closed this by misstake :-)

**Comment by timint** [comment]
No worries. :) I'm going to close this topic until further.
