### ISSUE TITLE
Can't connect to the website

### ISSUE THREAD

**Issue by Toulibre-hash** [litecart/litecart#352]
### What where you trying to do?
I'm trying to connect to the website since this morning

### What actually happened?
codes verifications sent by mail never received

### What did you expect to happen?
just connect normally to be able to translate french language

Not sure to write at the good place but this is the only one I could ..

Regards,
Toulibre

### LiteCart Version

Litecart website

### PHP Version

PHP xxx

### Is this a problem that can be reproduced in the demo platform (https://demo.litecart.net/admin)?

I don't know

### If this a visual problem that could be related to a browser. Which one?

Firefox

**Comment by timint** [comment]
Is it still an issue? I can access the site.

**Comment by Toulibre-hash** [comment]
Not an issue anymore, I can access again to the website, thanks.

**Comment by ghost** [comment]
Hello Tim, since a few days can't login on the website to write to the forum or to translate.
Code verification sent doesn't stay and refresh the page automatically before to click on login button.
Then my name appears like I'm connected but in fact not.
All my browser addons being off is no effect too.
Blessings and best wishes for the end of this year and after.

**Comment by timint** [comment]
@toutlibre I managed to find the cause in the JavaScript form assist code. Should be ok now.

**Comment by ghost** [comment]
@timint Thanks, it works !
